services:
  app-backend:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - app-database
    restart: always
    container_name: app-backend

  app-database:
    image: postgres:17-alpine
    container_name: app-database
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: SisInnovTech


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-application
    restart: always
    ports:
      - "4332:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@application.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - app-database
